version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: monthly 
    # interval: "weekly"
    # day: "wednesday"
  groups:
    maven-patch-group:
      update-types:
      - "minor"

  open-pull-requests-limit: 10
