version: 2

updates:
- package-ecosystem: "maven"
  directory: "/"
  schedule:
    # cron: minute hour day-of-month(1..31) month-of-year (1..12) day-of-week (0-6,SUN-SAT)
    # 04:15 on the 7th of each month.
    interval: "cron"
    cronjob: "15 4 7 * *"
    # interval: "monthly"
    # interval: "weekly"
    # day: "wednesday"
  groups:
    maven-patch-group:
      update-types:
      - "patch"

  open-pull-requests-limit: 10
