#!/usr/bin/bash
## Licensed under the terms of http://www.apache.org/licenses/LICENSE-2.0
# Compare code here with code in Jena.

if [ $# != 0 ]
then
    echo "Usage: $0" 1>&2
    exit 1
fi

## echo "==== IRI"
## DIR1=$HOME/ASF/jena5/jena-iri3986/src/main/java/org/apache/jena/rfc3986/
## DIR2=$HOME/ASF/x4ld/iri4ld/src/main/java/org/seaborne/rfc3986/

## echo "==== Langtag"
## DIR1=$HOME/ASF/jena5/jena-langtag/src/main/java/org/apache/jena/langtag/
## DIR2=$HOME/ASF/x4ld/lang4ld/src/main/java/org/seaborne/lang4ld/

if [ ! -e "$DIR1" ]
then
    echo "No such directory: $DIR1" 1>&2
    exit 1
fi

if [ ! -e "$DIR2" ]
then
    echo "No such directory: $DIR2" 1>&2
    exit 1
fi

FILES="$(cd $DIR1 ; find . -name \*.java)"
##echo $FILES

for F in $FILES
do
    FN1="$DIR1/$F"
    FN2="$DIR2/$F"
    if [ ! -e "$FN1" ]
    then
	echo "No such file: $FN1" 1>&2
	continue
    fi

    if [ ! -e "$FN2" ]
    then
	echo "No such file: $FN2" 1>&2
	continue
    fi

    echo "== Diff of $(basename $F) (jena<, iri4ld>)"
    diff "$FN1" "$FN2"
    echo
    
done

## echo "== Diff of $FN (jena<, iri4ld>)"
## echo diff -r "$DIR1" "$DIR2"
